### ISSUE TITLE
add links to github, contract on stellar.expert, and logos

### ISSUE THREAD

**Issue by antb123** [bp-ventures/lightecho-blog#3]
![image](https://github.com/bp-ventures/lightecho-blog/assets/17188302/cebd627d-3471-426a-90ba-5ce388f2a316)

**Comment by calarsenc** [comment]
Change social to X-logo and to new youtube logo

**Comment by santoshchaurasiya** [comment]
https://github.com/bp-ventures/lightecho-blog/pull/4
